export const FETCH_PARTIES_LOADING = "FETCH_PARTIES_LOADING";
export const FETCH_PARTIES_ERROR = "FETCHPARTIES_ERROR";
export const FETCH_PARTIES_SUCCESS = "FETCH_PARTIES_SUCCESS";
export const CHANGE_CURRENT_PARTY = "CHANGE_CURRENT_PARTY";

export const SAVE_PARTY_LOADING = "SAVE_PARTY_LOADING";
export const SAVE_PARTY_ERROR = "SAVE_PARTY_ERROR";
export const SAVE_PARTY_SUCCESS = "SAVE_PARTY_SUCCESS";
export const SAVE_PARTY_INPUT_CHANGE = "SAVE_PARTY_INPUT_CHANGE";

export const FETCH_GROUP_LOADING = "FETCH_GROUP_LOADING";

export const PARTIES_POST_REQUEST = "PARTIES_POST_REQUEST";
export const PARTIES_POST_SUCCESS = "PARTIES_POST_SUCCESS";
export const PARTIES_POST_FAILED = "PARTIES_POST_FAILED";

export const CURRENT_PARTIES_TRANSECATIONS_SUCCESS = "CURRENT_PARTIES_TRANSECATIONS_SUCCESS";


export const PARTIES_PURCHASE_BILL_REQUEST = "PARTIES_PURCHASE_BILL_REQUEST";
export const PARTIES_PURCHASE_BILL_FAILURE = "PARTIES_PURCHASE_BILL_FAILURE";

export const PARTIES_PAYMENT_OUT_SUCCESS = "PARTIES_PAYMENT_OUT_SUCCESS";
export const PARTIES_PAYMENT_OUT_REQUEST = "PARTIES_PAYMENT_OUT_REQUEST";
export const PARTIES_PAYMENT_OUT_FAILURE = "PARTIES_PAYMENT_OUT_FAILURE";
