export const FETCH_PARTIES_LOADING = "FETCH_PARTIES_LOADING";
export const FETCH_PARTIES_ERROR = "FETCHPARTIES_ERROR";
export const FETCH_PARTIES_SUCCESS = "FETCH_PARTIES_SUCCESS";

export const SAVE_PARTY_LOADING = "SAVE_PARTY_LOADING";
export const SAVE_PARTY_ERROR = "SAVE_PARTY_ERROR";
export const SAVE_PARTY_SUCCESS = "SAVE_PARTY_SUCCESS";
export const SAVE_PARTY_INPUT_CHANGE = "SAVE_PARTY_INPUT_CHANGE";
