
// requesting and falure handeling
export const ISLOADING = "ISLOADING";
export const PURCHASE_REQUEST = "PURCHASE_REQUEST";
export const PURCHASE_FAILURE = "PURCHASE_FAILURE";

// for getting PURCHASE BILLS
export const GET_PURCHASEBILL_SUCCESS = "GET_PURCHASEBILL_SUCCESS";

// for posting NEW BILLS
export const POST_PURCHASEBILL_SUCCESS = "POST_PURCHASEBILL_SUCCESS";

// export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
// export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
// export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
// export const INPUTCHANGE = "INPUTCHANGE";
