// requesting and falure handeling
export const ISLOADING = "ISLOADING";
export const REPORT_REQUEST = "REPORT_REQUEST";
export const REPORT_FAILURE = "REPORT_FAILURE";

// for getting PURCHASE BILLS
export const GET_SALEREPORT_SUCCESS = "GET_SALEREPORT_SUCCESS";
export const GET_PURCHASEREPORT_SUCCESS = "GET_PURCHASEREPORT_SUCCESS";
export const GET_DAYBOOK_SUCCESS = "GET_DAYBOOK_SUCCESS";
export const GET_ALLTRANSECTION_SUCCESS = "GET_ALLTRANSECTION_SUCCESS";



// export const GET_PAYOUTBILL_SUCCESS = "GET_PAYOUTBILL_SUCCESS";
// export const GET_PURCHASEORDER_SUCCESS = "GET_PURCHASEORDER_SUCCESS"
// export const GET_PURCHASERETURN_SUCCESS = "GET_PURCHASERETURN_SUCCESS";


