export const FETCH_EXPENSES_LOADING = "FETCH_EXPENSES_LOADING";
export const FETCH_EXPENSES_ERROR = "FETCHEXPENSES_ERROR";
export const FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS";
export const CHANGE_CURRENT_EXPENSE = "CHANGE_CURRENT_EXPENSE";

export const SAVE_EXPENSE_LOADING = "SAVE_EXPENSE_LOADING";
export const SAVE_EXPENSE_ERROR = "SAVE_EXPENSE_ERROR";
export const SAVE_EXPENSE_SUCCESS = "SAVE_EXPENSE_SUCCESS";

export const FETCH_GROUP_LOADING = "FETCH_GROUP_LOADING";

export const EXPENSES_POST_REQUEST = "EXPENSES_POST_REQUEST";
export const EXPENSES_POST_SUCCESS = "EXPENSES_POST_SUCCESS";
export const EXPENSES_POST_FAILED = "EXPENSES_POST_FAILED";

// Edit EXPENSE action types
export const EDIT_EXPENSE_LOADING = "EDIT_EXPENSE_LOADING";
export const EDIT_EXPENSE_ERROR = "EDIT_EXPENSE_ERROR";
export const SUCCESS_EDIT_EXPENSE = "SUCCESS_EDIT_EXPENSE";

// Delete EXPENSE action types
export const LOADING_DELETE_EXPENSE = "LOADING_DELETE_EXPENSE";
export const ERROR_DELETE_EXPENSE = "ERROR_DELETE_EXPENSE";
export const SUCCESS_DELETE_EXPENSE = "SUCCESS_DELETE_EXPENSE";

// Get Current EXPENSE Data action types
export const LOADING_GET_CURRENT_EXPENSE = "LOADING_GET_CURRENT_EXPENSE";
export const ERROR_GET_CURRENT_EXPENSE = "ERROR_GET_CURRENT_EXPENSE";
export const SUCCESS_GET_CURRENT_EXPENSE = "SUCCESS_GET_CURRENT_EXPENSE";

// Others
export const EXPENSES_PURCHASE_BILL_REQUEST = "EXPENSES_PURCHASE_BILL_REQUEST";
export const EXPENSES_PURCHASE_BILL_FAILURE = "EXPENSES_PURCHASE_BILL_FAILURE";
export const EXPENSES_PAYMENT_OUT_SUCCESS = "EXPENSES_PAYMENT_OUT_SUCCESS";
export const EXPENSES_PAYMENT_OUT_REQUEST = "EXPENSES_PAYMENT_OUT_REQUEST";
export const EXPENSES_PAYMENT_OUT_FAILURE = "EXPENSES_PAYMENT_OUT_FAILURE";
