// requesting and falure handeling
export const ISLOADING = "ISLOADING";
export const PURCHASE_REQUEST = "PURCHASE_REQUEST";
export const PURCHASE_FAILURE = "PURCHASE_FAILURE";

// for getting PURCHASE BILLS
export const GET_PURCHASEBILL_SUCCESS = "GET_PURCHASEBILL_SUCCESS";
export const GET_PAYOUTBILL_SUCCESS = "GET_PAYOUTBILL_SUCCESS";
export const GET_PURCHASEORDER_SUCCESS = "GET_PURCHASEORDER_SUCCESS"
export const GET_PURCHASERETURN_SUCCESS = "GET_PURCHASERETURN_SUCCESS";

// for posting NEW BILLS
export const POST_PURCHASEBILL_SUCCESS = "POST_PURCHASEBILL_SUCCESS";
export const POST_PURCHASEORDER_SUCCESS = "POST_PURCHASEORDER_SUCCESS";
export const POST_PURCHASERETURN_SUCCESS = "POST_PURCHASERETURN_SUCCESS";
export const POST_PAYOUT_SUCCESS = "POST_PAYOUTOUT_SUCCESS";


export const DELETE_PURCHASEBILL_SUCCESS = "DELETE_PURCHASEBILL_SUCCESS";
export const DELETE_PAYOUTBILL_SUCCESS = "DELETE_PAYOUTBILL_SUCCESS";
export const DELETE_PURCHASEORDER_SUCCESS = "DELETE_PURCHASEORDER_SUCCESS"
export const DELETE_PURCHASERETURN_SUCCESS = "DELETE_PURCHASERETURN_SUCCESS";


// export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
// export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
// export const INPUTCHANGE = "INPUTCHANGE";
