export const ISLOADING = "ISLOADING";
export const ISERROR = "ISERROR";
export const SUCCESS = "SUCCESS";
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const INPUTCHANGE = "INPUTCHANGE";

// Local Storage Keys
export const USER_DETAILS = "USER_DETAILS";
